menuentry "PaneBot Node" {
    icon \EFI\boot\themes\marlovious.boot\icons\os_debian.png
    volume YOUR-ESP-PARTUUID-HERE
    loader \EFI\BOOT\BOOTX64.EFI
    options "quiet splash loglevel=0 systemd.show_status=false vt.global_cursor_default=0"
    graphics on
}
