menuentry "PaneBot Node" {
    icon \EFI\refind\themes\marlovious.boot\icons\os_debian.png
    volume PANEBOOT-ESP-PARTUUID-HERE
    loader \EFI\debian\grubx64.efi
    graphics on
}

menuentry "SteamOS" {
    icon \EFI\refind\themes\marlovious.boot\icons\os_steam.png
    volume STEAMOS-ESP-PARTUUID-HERE
    loader \EFI\steamos\steamcl.efi
    options "quiet splash"
    graphics on
}
