# Marlovious Boot rEFInd config

timeout 1
use_nvram false

hideui arrows,hints,label
use_graphics_for linux
showtools reboot,shutdown,firmware

scanfor manual,external
scan_all_linux_kernels false
default_selection 1

include themes/marlovious.boot/theme.conf
include boots.conf
