# Marlovious Boot rEFInd theme

icons_dir themes/marlovious.boot/icons

banner themes/marlovious.boot/background.png
banner_scale fillscreen

selection_big   themes/marlovious.boot/icons/selection_big.png
selection_small themes/marlovious.boot/icons/selection_small.png

font themes/marlovious.boot/fonts/nimbus-mono-28.png
